### ISSUE TITLE
data type

### ISSUE THREAD

**Issue by shivam7494** [WDee/Deepsweep#1]
Can I use Deepsweep to analyze SNP chip data (specifically 777k bovine HD chip)

**Comment by WDee** [comment]
I see no reason ex-ante why this would not work

From: shivam7494 ***@***.***>
Sent: Thursday, July 29, 2021 9:14 PM
To: WDee/Deepsweep ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [WDee/Deepsweep] data type (#1)


Can I use Deepsweep to analyze SNP chip data (specifically 777k bovine HD chip)

**Comment by shivam7494** [comment]
Thank you, sir. I'm planning to use this for my PhD research project.
